# Generated by Django 5.0.3 on 2024-05-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='lname',
        ),
    ]
